#define NUITKA_COMPANY_NAME "Cshtarn"
#define NUITKA_VERSION_COMBINED "0.0.1.0-0...0...1...0"
#define _NUITKA_ONEFILE_COMPRESSION 1
#define _NUITKA_ONEFILE_TEMP 1
#define _NUITKA_ONEFILE_TEMP_SPEC "%TEMP%\\onefile_%PID%_%TIME%"
